trigger:
- main  # Adjust this to your default branch or the branch you want to trigger the pipeline

pool:
  name: 'gitopsmlk'  # The name of your self-hosted agent pool

variables:
  GIT_REPO_URL: 'https://github.com/MalekFarhani/phpapp.git'  # URL of your Git repository
  ACR_NAME: 'acrmlk'  # Your Azure Container Registry name
  IMAGE_NAME: 'phpapp'  # The name you want for your Docker image
  IMAGE_TAG: '$(Build.BuildId)'  # Unique tag for your Docker image

steps:
- script: |
    echo "Step 1: Cloning the repository"
    git clone $(GIT_REPO_URL)
  displayName: 'Git Clone'

- script: |
    echo "Step 2: Building the Docker image"
    cd phpapp  # Navigate to the directory where the Dockerfile is located
    sudo docker build -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(IMAGE_TAG) .
  displayName: 'Docker Build'

- script: | 
    sudo docker login acrmlk.azurecr.io --username 00000000-0000-0000-0000-000000000000 --password eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlhLWUw6S1pSWDpRNU5UOlFKTk86RFRCVzpSM1dXOjNKWVM6NE9EWTpFVFJYOlk3VDI6WkY1WToyQUZNIn0.eyJqdGkiOiI0MjhjMTIxMi05ZGFlLTRmNjktYTk4OS1mMjRlMGE4NGNkYjkiLCJzdWIiOiIyNmViYTRmMi0xMWZkLTRmZDctYjZkOC1mZTFkYTU1YjlmZDkiLCJuYmYiOjE3MjQ3NjI2NTQsImV4cCI6MTcyNDc3NDM1NCwiaWF0IjoxNzI0NzYyNjU0LCJpc3MiOiJBenVyZSBDb250YWluZXIgUmVnaXN0cnkiLCJhdWQiOiJhY3JtbGsuYXp1cmVjci5pbyIsInZlcnNpb24iOiIxLjAiLCJyaWQiOiJmODY0YzNkMmJjYWE0YTI2YjYxNmFmYzE5ZWM1YWRkNyIsImdyYW50X3R5cGUiOiJyZWZyZXNoX3Rva2VuIiwiYXBwaWQiOiI5NTkzOWFkZi04OTRkLTRiM2QtODVmNi0zYmY0OWI2YTkzYjQiLCJ0ZW5hbnQiOiI5NzQwNDA3Mi0xNWJjLTRiZTItYWFkOS1jNWQyYjA3NTQxZWIiLCJwZXJtaXNzaW9ucyI6eyJhY3Rpb25zIjpbInJlYWQiLCJ3cml0ZSIsImRlbGV0ZSIsIm1ldGFkYXRhL3JlYWQiLCJtZXRhZGF0YS93cml0ZSIsImRlbGV0ZWQvcmVhZCIsImRlbGV0ZWQvcmVzdG9yZS9hY3Rpb24iXX0sInJvbGVzIjpbXX0.kbZejqNKEBygsXZRM8yX_VNuP9cBB3BZcuhHIsGKQVN0GCQG59qDnp0Qvi_TulJSKC5GceOV2YDxKFxyXJAfqYh_tOL2ePGvZQheGFN0iowyo3RA96JVYYa1vVYKNYdIsBMkvuLOszJ7COoDtxE-PEVL-XsGEryM7c-BqT2XymPjU4DZUG2slxXhdCQ6O1x-xOkeJqNaqXUH4iOE825LuAXBEHqaO4knKtmx3pr7_E5PJWJNWltYY25Jx8SL_7rUwXMHrtziUMZiTo-lPjQ3MqbDX_v2Q_vjN026rKGtT4CfaXGj1dNh84seh46mwIJ6dNuCBqBJrDoj7WivIwvWHw
  displayName: 'login'
- script: | 
    docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(IMAGE_TAG)
  displayName: 'push'
- script: |
    echo "Step 4: Verifying the image in ACR"
    az acr repository show-tags --name $(ACR_NAME) --repository $(IMAGE_NAME) --query "contains(@, '$(IMAGE_TAG)')"
  displayName: 'Verify Image in ACR'